### ISSUE TITLE
Can find the c3s binary

### ISSUE THREAD

**Issue by wenluo711** [PacificBiosciences/c3s#1]
Hi Armin,

I'm trying to use pacbio clustered ccs reads to generate consensus fasta described in the pbampliconclustering github page. Your tool c3s is recommended there. But I don't seem to be able find a executable binary c3s in the github repo here. 

Am I missing any step?
Thanks for developing the tool!

Best,
Wen

**Comment by armintoepfer** [comment]
https://github.com/armintoepfer/c3s/releases/tag/v0.0.1

![image](https://user-images.githubusercontent.com/1433286/90320358-e91b4180-df40-11ea-8eea-0fed102cc6af.png)

;)
